Adds upgradability to L2 Migrator contract
livepeer/arbitrum-lpt-bridge pull request #64
Opened 2022-02-03 20:14 UTC by kautukkundan

**What does this pull request do? Explain your changes. (required)**

Adds upgradability to L2 Migrator contract in case the contract needs to be updated. Using the same ManagerProxy and ManagerProxyTarget pattern used by [protocol contracts ](https://github.com/livepeer/protocol/blob/streamflow/contracts/ManagerProxy.sol).

**Specific updates (required)**

- Copied contracts from protocol repo 
- Updated L2 Migrator to use ManagerProxyTarget
- Updated unit tests 

**How did you test each of these updates (required)**

ran unit tests

**Does this pull request close any open issues?**

**Checklist:**

- [x] README and other documentation updated
- [x] All tests using `yarn test` pass

2022-02-03 22:02 UTC, yondonfu requested changes
Coverage is down with the introduce of the contracts in the `proxy` folder. Since the tests for those contracts are already in the protocol repo we can ignore them in the `.solcover.js` file since the code coverage is addressed elsewhere.

2022-02-04 12:11 UTC, kautukkundan commented on contracts/L2/gateway/L2Migrator.sol
> +    address public bondingManagerAddr;
tracking here https://github.com/livepeer/arbitrum-lpt-bridge/issues/65

2022-02-04 12:11 UTC, kautukkundan commented on contracts/L2/gateway/L2Migrator.sol
> +     * - initialize() function must be called immediately after deployment
fixed in 010e074

2022-02-04 13:30 UTC, yondonfu approved these changes
LGTM!

2022-02-04 15:25 UTC, merged